#!/usr/bin/python3
#+
# HarfPy example: recreating selected snippets of Indic text from
# <http://rishida.net/scripts/indic-overview/>. Fonts needed:
#
#      Name                    Debian package name
#      ----                    -------------------
#    Lohit Devanagari           fonts-lohit-deva
#    Lohit Gurmukhi             fonts-lohit-guru
#    Lohit Kannada              fonts-lohit-knda
#    Lohit Odia                 fonts-lohit-orya
#    Lohit Tamil                fonts-lohit-taml
#
# Copyright 2017 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import os
import warnings
# import freetype2 as ft # use Qahirah instance
import qahirah as qah
from qahirah import \
    CAIRO, \
    Colour, \
    Vector
ft = qah.get_ft_lib()
import harfbuzz as hb
from harfbuzz import \
    HARFBUZZ as HB

#+
# Useful stuff
#-

def find_face(family_name) :
    font = ft.find_face(family_name)
    if font.family_name != family_name :
        warnings.warn("font “%s” not found, substituting “%s” instead" % (family_name, font.family_name))
    #end if
    return \
        font
#end find_face

#+
# Samples
#
# Most of these fonts, other than Lohit Devanagari, don’t have
# Roman characters, and also the presence of Roman characters
# seems to confuse their shaping algorithms.
#-

text_samples = \
    ( # sequence of (fontspec, lines) tuples
        (
            "Lohit Devanagari",
            (
                #"Hindi "
                "\u0939" # DEVANAGARI LETTER HA
                "\u093F" # DEVANAGARI VOWEL SIGN I
                "\u0902" # DEVANAGARI SIGN ANUSVARA
                "\u0926" # DEVANAGARI LETTER DA
                "\u0940", # DEVANAGARI VOWEL SIGN II

                #"Yogi "
                "\u092F" # DEVANAGARI LETTER YA
                "\u094B" # DEVANAGARI VOWEL SIGN O
                "\u0917" # DEVANAGARI LETTER GA
                "\u094D" # DEVANAGARI SIGN VIRAMA
                "\u092F", # DEVANAGARI LETTER YA
            ),
        ),
        (
            "Lohit Kannada",
            (
                #"Simha "
                "\u0CB8" # KANNADA LETTER SA
                "\u0C82" # KANNADA SIGN ANUSVARA
                "\u0CB9", # KANNADA LETTER HA

                #"Punaha "
                "\u0CAA" #  KANNADA LETTER PA
                "\u0CC1" #  KANNADA VOWEL SIGN U
                "\u0CA8" #  KANNADA LETTER NA
                "\u0C83", # KANNADA SIGN VISARGA

                #"Kri "
                "\u0C95" # KANNADA LETTER KA
                "\u0CCD" # U+0CCD KANNADA SIGN VIRAMA
                "\u0CB0" # KANNADA LETTER RA
                "\u0CBF", # KANNADA VOWEL SIGN I
            ),
        ),
        (
            "Lohit Odia",
            (
                #"Anka "
                "\u0B05" # ORIYA LETTER A
                "\u0B02" # U+0B02 ORIYA SIGN ANUSVARA
                "\u0B15", # U+0B15 ORIYA LETTER KA
            ),
        ),
        (
            "Lohit Gurmukhi",
            (
                #"Munda "
                "\u0A2E" # GURMUKHI LETTER MA
                "\u0A41" # GURMUKHI VOWEL SIGN U
                "\u0A70" # GURMUKHI TIPPI
                "\u0A21" # GURMUKHI LETTER DDA
                "\u0A3E", # GURMUKHI VOWEL SIGN AA

                #"Shat "
                "\u0A38" # GURMUKHI LETTER SA
                "\u0A3C" #  GURMUKHI SIGN NUKTA
                "\u0A3E" #  GURMUKHI VOWEL SIGN AA
                "\u0A02" #  GURMUKHI SIGN BINDI
                "\u0A24", #  GURMUKHI LETTER TA
            ),
        ),
        (
            "Lohit Tamil",
            (
                #"Fisu "
                "\u0B83" # TAMIL SIGN VISARGA
                "\u0BAA" # TAMIL LETTER PA
                "\u0BC0" # TAMIL VOWEL SIGN II
                "\u0B9A" # TAMIL LETTER CA
                "\u0BC1", # TAMIL VOWEL SIGN U

                #"Ziroks "
                "\u0B83" # TAMIL SIGN VISARGA
                "\u0B9C" # TAMIL LETTER JA
                "\u0BBF" # TAMIL VOWEL SIGN I
                "\u0BB0" # TAMIL LETTER RA
                "\u0BBE" # TAMIL VOWEL SIGN AA
                "\u0B95" # TAMIL LETTER KA
                "\u0BCD" # TAMIL SIGN VIRAMA
                "\u0BB8" # TAMIL LETTER SA
                "\u0BCD", # TAMIL SIGN VIRAMA
            ),
        ),
    )

#+
# Mainline
#-

label_text_size = 36
sample_text_size = 36
roman_face = find_face("DejaVu Sans")
roman_face.set_char_size(size = label_text_size, resolution = qah.base_dpi)
hb_roman = hb.Font.ft_create(roman_face)
buf = hb.Buffer.create()
line_pos = Vector(0, 0)
sample_indent = 40
max_line_width = 0
glyph_renders = []
for font_spec, text_lines in text_samples :
    line_spacing = Vector(0, roman_face.size["metrics"]["height"])
    line_pos += line_spacing * Vector(1, 1.5)
    buf.reset()
    buf.add_str(font_spec)
    buf.guess_segment_properties()
    hb.shape(hb_roman, buf)
    glyphs, end_glyph_pos = buf.get_glyphs(line_pos)
    max_line_width = max(max_line_width, end_glyph_pos.x)
    glyph_renders.append({"ft_face" : roman_face, "size" : label_text_size, "glyph_lines" : [glyphs]})

    ft_face = find_face(font_spec)
    ft_face.set_char_size(size = sample_text_size, resolution = qah.base_dpi)
    hb_font = hb.Font.ft_create(ft_face)
    line_spacing = Vector(0, ft_face.size["metrics"]["height"])
    glyph_lines = []
    for text_line in text_lines :
        line_pos += line_spacing
        buf.reset()
        buf.add_str(text_line)
        buf.guess_segment_properties()
        hb.shape(hb_font, buf)
        glyphs, end_glyph_pos = buf.get_glyphs(line_pos + Vector(sample_indent, 0))
        glyph_lines.append(glyphs)
        max_line_width = max(max_line_width, end_glyph_pos.x)
    #end for
    glyph_renders.append({"ft_face" : ft_face, "size" : sample_text_size, "glyph_lines" : glyph_lines})
#end for

margin = Vector(10, 10)
figure_dimensions = round(Vector(max_line_width, line_pos.y) + margin * Vector(3, 4))
pix = qah.ImageSurface.create \
  (
    format = CAIRO.FORMAT_RGB24,
    dimensions = figure_dimensions
  )
ctx = \
    (qah.Context.create(pix)
        .translate(margin)
        .set_source_colour(Colour.grey(1))
        .paint()
        .set_source_colour(Colour.grey(0))
    )
for glyph_render in glyph_renders :
    qah_face = qah.FontFace.create_for_ft_face(glyph_render["ft_face"])
    ctx.set_font_face(qah_face)
    ctx.set_font_size(glyph_render["size"])
    for glyphs in glyph_render["glyph_lines"] :
        ctx.show_glyphs(glyphs)
    #end for
#end for
pix.flush().write_to_png("%s.png" % os.path.basename(sys.argv[0]))
